listen=":8081"

[dbservers]
    [dbservers.mydb]
        host = "127.0.0.1"
        port = 5432
        dbname = "mydb"
        user = "postgres"
        password = "admin"
    [dbservers.mydb1]
        host = "127.0.0.1"
        port = 5432
        dbname = "mydb1"
        user = "postgres"
        password = "admin"
[redisservers]
    [redisservers.cache]
        addr = "127.0.0.1:6379"
        password = ""
        db = 0
